const music = [
{'title': "Zombie", artist: "The Cranberries", album: "No Need To Argue"},
{'title': "Thinking Out Loud", artist: "Ed Sheeran", album: "x (Deluxe Edition"},
{'title': "On Bended Knee", artist: "Boyz II Men", album: "II"},
{'title': "I'll Make Love To You", artist: "Boyz II Men", album: "II"},
{'title': "Just A Friend", artist: "Biz Markie", album: "Just A Friend - EP"},
{'title': "Wonderful Tonight", artist: "Eric Clapton", album: "Slowhand"},
{'title': "Don't Dream It's Over", artist: "Crowded House", album: "Crowded House"},
{'title': "No Love (feat. Lil Wayne)", artist: "Eminem", album: "Recovery"},
{'title': "Back At One", artist: "Brian McKnight", album: "Back At One"},
{'title': "Get Money", artist: "Junior M.A.F.I.A.", album: "Once Upon A Time in 95"},
{'title': "Holding Out for a Hero", artist: "Bonnie Tyler", album: "Secret Dreams And Forbidden Fire"},
{'title': "For You I Will", artist: "Monica", album: "The Boy Is Mine"},
{'title': "Family Affair", artist: "Mary J. Blige", album: "No More Drama"},
{'title': "Another Night (Radio Mix)", artist: "Real McCoy", album: "Platinum & Gold Collection"},
{'title': "Beautiful Life (Remastered)", artist: "Ace of Base", album: "Beautiful Life (The Remixes)"},
{'title': "Bailamos (Wild Wild West/Soundtrack Version)", artist: "Enrique Iglesias", album: "Enrique"},
{'title': "Blue (Da Ba Dee) (DJ Ponte Ice Pop Radio)", artist: "Eiffel 65", album: "Europop"},
{'title': "Torikago (From \"Darling in the FranXX\")", artist: "Fonzi M", album: "Anime Piano Music Collection in Spring, Vol. 2"},
{'title': "Shadows of a Setting Sun (Shinsuke Nakamura)", artist: "Shadows of The Sun", album: "Shadows of a Setting Sun (Shinsuke Nakamura)"},
{'title': "Kiss of Death (Produced by Hyde)", artist: "Mika Nakashima", album: "Kiss of Death (Produced by Hyde)"},
{'title': "Beautiful World (From \"Darling in the FranXX\")", artist: "Fonzi M", album: "Anime Piano Music Collection in Spring, Vol. 2"},
{'title': "Lean Back (Album Version Explicit)", artist: "Terror Squad", album: "True Story"},
{'title': "I Wanna Love You", artist: "Akon", album: "Konvicted"},
{'title': "This Fire", artist: "Killswitch Engage", album: "As Daylight Dies [Special Edition]"},
{'title': "The Future (Asuka)", artist: "WWE & CFO$", album: "The Future (Asuka)"},
{'title': "Yeah!", artist: "Usher", album: "Confessions (Special Edition)"},
{'title': "Somebody That I Used To Know (feat. Kimbra)", artist: "Gotye", album: "Making Mirrors"},
{'title': "Undisputed (The Undisputed Era)", artist: "WWE & CFO$", album: "Undisputed (The Undisputed Era)"},
{'title': "Lupin the Third Theme '78", artist: "Testuya Yoshikawa", album: "Japan Animesong Collection Vol. 18 [Anison Japan]"},
{'title': "Worlds Apart (Sami Zayn)", artist: "WWE & CFO$", album: "Worlds Apart (Sami Zayn)"},
{'title': "Cold Rock A Party", artist: "MC Lyte", album: "Bad As I Wanna B"},
{'title': "Gangsta's Paradise (feat. L.V.)", artist: "Coolio", album: "Gangsta's Paradise"},
{'title': "All My Life", artist: "K-Ci & JoJo", album: "Love Always"},
{'title': "Believe", artist: "Cher", album: "Believe"},
{'title': "It Wasn't Me (feat. Ricardo Ducent)", artist: "Shaggy", album: "The Boombastic Collection - Best of Shaggy"},
{'title': "California", artist: "Grimes", album: "Art Angels"},
{'title': "You Can Do It (Feat. Mack 10 And Ms Toi)", artist: "Ice Cube", album: "War & Peace Vol. 2 (The Peace Disc)"},
{'title': "Kill V. Maim", artist: "Grimes", album: "Art Angels"},
{'title': "Somebody To Love", artist: "Queen", album: "A Day At The Races"},
{'title': "Amore", artist: "BABYMETAL", album: "METAL RESISTANCE"},
{'title': "Glorious Domination (Bobby Roode)", artist: "WWE & CFO$", album: "Glorious Domination (Bobby Roode)"},
{'title': "Hallelujah", artist: "Bamboo", album: "Light Peace Love"},
{'title': "HeadBangeeeeerrrrr!!!!!", artist: "BABYMETAL", album: "BabyMetal"},
{'title': "Phenomenal (AJ Styles)", artist: "WWE & CFO$", album: "Phenomenal (AJ Styles)"},
{'title': "All Of The Lights", artist: "Kanye West", album: "My Beautiful Dark Twisted Fantasy"},
{'title': "line!", artist: "BABYMETAL", album: "BabyMetal"},
{'title': "Road of Resistance", artist: "BABYMETAL", album: "METAL RESISTANCE"},
{'title': "Ijime, Dame, Zettai", artist: "BABYMETAL", album: "BabyMetal"},
{'title': "Gimme Chocolate!!", artist: "BABYMETAL", album: "BabyMetal"},
{'title': "Megitsune", artist: "BABYMETAL", album: "BabyMetal"},
{'title': "KARATE", artist: "BABYMETAL", album: "METAL RESISTANCE"},
{'title': "I Believe In A Thing Called Love", artist: "The Darkness", album: "Permission To Land"},
{'title': "Jumpman", artist: "Drake & Future", album: "What A Time To Be Alive"},
{'title': "Only Time", artist: "Enya", album: "A Day Without Rain"},
{'title': "Sandstorm (Original Mix)", artist: "Darude", album: "Sandstorm"},
{'title': "The Rising Sun (Shinsuke Nakamura)", artist: "WWE & CFO$", album: "The Rising Sun (Shinsuke Nakamura)"},
{'title': "Overnight Celebrity", artist: "Twista", album: "Kamikaze"},
{'title': "Chandelier", artist: "Sia", album: "1000 Forms Of Fear"},
{'title': "True", artist: "Spandau Ballet", album: "Once More"},
{'title': "Lovefool (Radio Edit)", artist: "The Cardigans", album: "First Band On The Moon"},
{'title': "Ironic (2015 Remastered)", artist: "Alanis Morissette", album: "Jagged Little Pill (Remastered)"},
{'title': "Back To Back", artist: "Drake", album: "Back To Back"},
{'title': "Drive", artist: "Incubus", album: "Make Yourself"},
{'title': "Black Skinhead", artist: "Kanye West", album: "Yeezus"},
{'title': "Shut Up and Dance", artist: "WALK THE MOON", album: "TALKING IS HARD"},
{'title': "Marvin Gaye (feat. Meghan Trainor)", artist: "Charlie Puth", album: "Some Type Of Love"},
{'title': "Ghost", artist: "Ella Henderson", album: "Chapter One (Deluxe Version)"},
{'title': "Achy Breaky Heart", artist: "Billy Ray Cyrus", album: "Some Gave All"},
{'title': "Bailamos", artist: "Latin Band", album: "Latino, Vol. 1 (1998)"},
{'title': "GDFR (feat. Sage The Gemini & Lookas)", artist: "Flo Rida", album: "GDFR (feat. Sage The Gemini & Lookas)"},
{'title': "Let Me Blow Ya Mind (feat. Gwen Stefani)", artist: "Eve", album: "Scorpion"},
{'title': "Tubthumping", artist: "Chumbawamba", album: "Tubthumper"},
{'title': "Jump Around", artist: "House Of Pain", album: "House Of Pain"},
{'title': "Footloose", artist: "Kenny Loggins", album: "The Essential Kenny Loggins"},
{'title': "Baby, I Love Your Way / Freebird", artist: "Will To Power", album: "The Best Year Of My Life: 1989"},
{'title': "Turning Japanese", artist: "The Vapors", album: "Turning Japanese - Best Of The Vapors"},
{'title': "Kokomo", artist: "The Beach Boys", album: "50 Big Ones"},
{'title': "Under The Bridge", artist: "Red Hot Chili Peppers", album: "Blood Sugar Sex Magik"},
{'title': "Killing Me Softly", artist: "Fugees", album: "The Score"},
{'title': "Don't Speak", artist: "No Doubt", album: "Tragic Kingdom"},
{'title': "Creep", artist: "Radiohead", album: "Pablo Honey"},
{'title': "Catch Your Breath (Finn Bálor)", artist: "WWE & CFO$", album: "Catch Your Breath (Finn Bálor)"},
{'title': "Ms. Fat Booty", artist: "Mos Def", album: "Black On Both Sides"},
{'title': "Funky Town", artist: "Lipps Inc.", album: "Paradas Continuas"},
{'title': "Everybody Everybody (Le Freak Mix) (feat. Martha Wash)", artist: "Black Box", album: "Everybody Everybody"},
{'title': "Informer", artist: "Snow", album: "Rhino Hi-Five: Rap [Vol 1]"},
{'title': "Gonna Make You Sweat (Everybody Dance Now)", artist: "C+C Music Factory", album: "Super Hits"},
{'title': "Sweat (A La La La La Long)", artist: "Inner Circle", album: "Blazzin' Fire"},
{'title': "Two Princes", artist: "Spin Doctors", album: "Pocket Full Of Kryptonite"},
{'title': "Together Again", artist: "Janet Jackson", album: "Best Of Number Ones"},
{'title': "Bump, Bump, Bump (feat. P. Diddy)", artist: "B2K", album: "Pandemonium!"},
{'title': "Send Me On My Way", artist: "Rusted Root", album: "When I Woke"},
{'title': "If You Come Back", artist: "Blue", album: "All Rise"},
{'title': "Sorry Seems To Be The Hardest Word (feat.Elton John)", artist: "Blue", album: "One Love"},
{'title': "Fly By", artist: "Blue", album: "All Rise"},
{'title': "Ghetto Supastar (That Is What You Are) (feat. Ol' DB & Mya)", artist: "Pras Michel", album: "Bulworth The Soundtrack"},
{'title': "Let It Go", artist: "Idina Menzel", album: "Frozen (Original Motion Picture Soundtrack)"},
{'title': "Firework", artist: "Katy Perry", album: "Teenage Dream"},
{'title': "Sweet Child O' Mine", artist: "Guns N' Roses", album: "Appetite For Destruction"},
{'title': "Hey Ya! (Radio Mix / Club Mix)", artist: "OutKast", album: "Speakerboxxx/The Love Below (Deluxe)"},
{'title': "No Diggity (feat. Dr. Dre & Queen Pen)", artist: "Blackstreet", album: "Another Level"},
{'title': "We Are Young (feat. Janelle Monáe)", artist: "fun.", album: "Some Nights"},
{'title': "POWER", artist: "Kanye West", album: "My Beautiful Dark Twisted Fantasy"},
{'title': "Jesus Walks", artist: "Kanye West", album: "Def Jam 25: DJ Bring That Back"},
{'title': "Gold Digger (Album Version Edited) (feat. Jamie Foxx)", artist: "Kanye West", album: "Late Registration"},
{'title': "Through The Wire (Explicit)", artist: "Kanye West", album: "The College Dropout (Explicit)"},
{'title': "Slow Jamz", artist: "Kanye West", album: "The College Dropout"},
{'title': "Swimming Pools (Drank) (Extended Version)", artist: "Kendrick Lamar", album: "good kid, m.A.A.d city"},
{'title': "Dancing On The Ceiling", artist: "Lionel Richie", album: "Dancing On The Ceiling"},
{'title': "Thug Passion", artist: "2Pac", album: "All Eyez On Me"},
{'title': "Torn", artist: "Natalie Imbruglia", album: "Left Of The Middle / White Lillies Island"},
{'title': "Hanging By a Moment", artist: "Lifehouse", album: "No Name Face"},
{'title': "Because The Night (MTV Unplugged Version) [Live]", artist: "10,000 Maniacs", album: "Campfire Songs: The Popular, Obscure and Unknown Recordings of 10,000 Maniacs"},
{'title': "The Sign (Remastered)", artist: "Ace of Base", album: "Greatest Hits"},
{'title': "I Wanna Dance with Somebody (Who Loves Me)", artist: "Whitney Houston", album: "Whitney"},
{'title': "Run-Around", artist: "Blues Traveler", album: "Four"},
{'title': "Sunshine (feat. Anthony Hamilton)", artist: "Twista", album: "Kamikaze"},
{'title': "Can't Nobody Hold Me Down (feat. Mase)", artist: "Puff Daddy & The Family", album: "No Way Out"},
{'title': "Nigga What, Nigga Who (Originator 99) (feat. Big Jaz)", artist: "Jay Z", album: "Vol.2 ... Hard Knock Life"},
{'title': "Still Not a Player (Radio Version) (feat. Joe)", artist: "Big Pun", album: "Capital Punishment"},
{'title': "ATLiens", artist: "OutKast", album: "ATLiens"},
{'title': "Can I Get A... (feat. Amil & Ja Rule)", artist: "Jay Z", album: "Vol.2 ... Hard Knock Life"},
{'title': "Poetic Justice (feat. Drake)", artist: "Kendrick Lamar", album: "good kid, m.A.A.d city"},
{'title': "Killing Me Softly with His Song", artist: "Fugees", album: "The Score"},
{'title': "What I Got", artist: "Sublime", album: "Sublime Greatest Hits"},
{'title': "Are You Gonna Go My Way", artist: "Lenny Kravitz", album: "Are You Gonna Go My Way"},
{'title': "Say My Name", artist: "Destiny's Child", album: "The Writing's On The Wall"},
{'title': "Closing Time", artist: "Semisonic", album: "Feeling Strangely Fine"},
{'title': "Wonderwall (Remastered)", artist: "Oasis", album: "(What's the Story) Morning Glory? [Remastered]"},
{'title': "This Is How We Do It", artist: "Montell Jordan", album: "This Is How We Do It"},
{'title': "Stay", artist: "Lisa Loeb & Nine Stories", album: "Tails"},
{'title': "Kiss From A Rose", artist: "Seal", album: "Seal [1994]"},
{'title': "What's Up?", artist: "4 Non Blondes", album: "Bigger, Better, Faster, More!"},
{'title': "More Than Words", artist: "Extreme", album: "Extreme II: Pornograffitti"},
{'title': "It Must Have Been Love (From \"Pretty Woman\")", artist: "Edward Miller & His Orchestra", album: "Films & Love (Le Piu' Belle Canzoni Da Film)"},
{'title': "Where'd You Go (feat. Holly Brook & Jonah Matranga)", artist: "Fort Minor", album: "The Rising Tied"},
{'title': "Driver's High", artist: "L'Arc-en-Ciel", album: "Clicked Singles Best 13"},
{'title': "Aria", artist: "Kalafina", album: "Seventh Heaven"},
{'title': "Natsu No Ringo", artist: "Kalafina", album: "Bluestars"},
{'title': "Your Body", artist: "Pretty Ricky", album: "Halik"},
{'title': "Sinta", artist: "Aegis", album: "Exodus"},
{'title': "Always On Time (feat. Ashanti)", artist: "Ja Rule", album: "Vivid"},
{'title': "Cult of Personality", artist: "Living Colour", album: "Doggystyle"},
{'title': "Gin And Juice (feat. Dat Nigga Daz)", artist: "Snoop Dogg", album: "Doggystyle"},
{'title': "I Can", artist: "Nas", album: "Greatest Hits"},
{'title': "It's a Party (feat. Zhane)", artist: "Busta Rhymes", album: "The Coming"},
{'title': "Itoshigo yo", artist: "Rurutia", album: "R"},
{'title': "Royals", artist: "Lorde", album: "Pure Heroine"},
{'title': "One Love", artist: "Blue", album: "One Love"},
{'title': "You Make Me Wanna", artist: "Blue", album: "One Love"},
];

export default music;